<a href="https://colab.research.google.com/github/lucasdevromero/Aula1-Readme/blob/main/Tratamento_relat%C3%B3rio_SLA_Inbound.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
!pip install gspread
!pip install gspread-dataframe
!pip install --upgrade gspread google-auth google-auth-oauthlib google-auth-httplib2

Requirement already satisfied: gspread in /usr/local/lib/python3.11/dist-packages (6.2.0)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from gspread) (2.39.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from gspread) (1.2.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.2.2)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2025.1.31)
Requirement already satisfied: gspread-dataframe in /usr/local/lib/python3.11/dist-packages (4.0.0)
Requirement already satisfied: gspread>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from gspread-dataframe) (6.2.0)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from gspread-dataframe) (2.2.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from gspread-dataframe) (1.17.0)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from gspread>=3.0.0->gspread-dataframe) (2.39.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from gspread>=3.0.0->gspread-dataframe) (1.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->gspread-dataframe) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->gspread-dataframe) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->gspread-dataframe) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->gspread-dataframe) (2025.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread>=3.0.0->gspread-dataframe) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread>=3.0.0->gspread-dataframe) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread>=3.0.0->gspread-dataframe) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread-dataframe) (2.0.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread>=3.0.0->gspread-dataframe) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread-dataframe) (3.2.2)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread-dataframe) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread-dataframe) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread-dataframe) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread-dataframe) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread-dataframe) (2025.1.31)
Requirement already satisfied: gspread in /usr/local/lib/python3.11/dist-packages (6.2.0)
Requirement already satisfied: google-auth in /usr/local/lib/python3.11/dist-packages (2.39.0)
Requirement already satisfied: google-auth-oauthlib in /usr/local/lib/python3.11/dist-packages (1.2.2)
Requirement already satisfied: google-auth-httplib2 in /usr/local/lib/python3.11/dist-packages (0.2.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from google-auth-oauthlib) (2.0.0)
Requirement already satisfied: httplib2>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from google-auth-httplib2) (0.22.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2>=0.19.0->google-auth-httplib2) (3.2.3)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.2)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (2025.1.31)

In [18]:
from google.colab import auth
import gspread

# Realizar a autenticação do usuário
auth.authenticate_user()

# Usar a função gspread.authorize() para autorizar o acesso ao Google Sheets
from google.auth import default

# Pega as credenciais de autenticação do Google
creds, _ = default()

# Autoriza o acesso ao Google Sheets usando as credenciais obtidas
gc = gspread.authorize(creds)

In [19]:
from google.colab import auth
import gspread
from google.auth import default
import pandas as pd
from gspread_dataframe import get_as_dataframe

# Realizar a autenticação do usuário
auth.authenticate_user()

# Obter as credenciais do Google
creds, _ = default()

# Autorizar o acesso ao Google Sheets
gc = gspread.authorize(creds)

# Defina os IDs das planilhas que você deseja acessar
planilha_ids = [
    '1pZDTGCURaFJktzmfJnmOtBGOYiLGGwhNVz81Cug8Cm0',  # ID da primeira planilha
    '1BXtUjGRhXy8P4HUibJj6g5vIR6za3qMku9UBgkf4Xrw',  # ID da segunda planilha
    '1XrY-Ywj7tUdIel4Z8kkdBcIQKlCP-LeioQurPMpwCxw',  # ID da segunda planilha
]

# Acessar a primeira planilha e suas abas 0 e 1
spreadsheet_1 = gc.open_by_key(planilha_ids[0])

# Acesse as abas 0 e 1
worksheet_1_0 = spreadsheet_1.get_worksheet(0)


# Carregar as abas 0 e 1 em DataFrames
# Não existe mais df_1_0 = get_as_dataframe(worksheet_1_0)
df_1_1 = get_as_dataframe(worksheet_1_0)

# Acessar a segunda planilha e a aba 2
spreadsheet_2 = gc.open_by_key(planilha_ids[1])

# Acesse a aba 2
worksheet_2_2 = spreadsheet_2.get_worksheet(2)

# Carregar a aba 2 em um DataFrame
df_2_2 = get_as_dataframe(worksheet_2_2)

# Acessar a segunda planilha e a aba 2
spreadsheet_3 = gc.open_by_key(planilha_ids[2])

# Acesse a aba 2
worksheet_3_0 = spreadsheet_3.get_worksheet(0)

# Carregar a aba 2 em um DataFrame
df_3_1 = get_as_dataframe(worksheet_3_0)


# Não existe mais display(df_1_0)
#display(df_1_1)
#display(df_2_2)
#display(df_3_1)

In [20]:
#Tratamento das bases de dados SAP:
# Concatenando as colunas de data e hora em uma nova coluna
# Não existe mais df_1_0['Data_e_Hora'] = df_1_0['Dta.criação'] + ' ' + df_1_0['Criado às']

# Convertendo a nova coluna para tipo datetime
# Não existe mais df_1_0['Data_e_Hora'] = pd.to_datetime(df_1_0['Data_e_Hora'])

# Exibindo o DataFrame com a nova coluna datetime
#print("\nDataFrame com a coluna 'datetime':")
#display(df_1_0)

#df_1_1
# Concatenando as colunas de data e hora em uma nova coluna
df_1_1['Data_e_Hora'] = df_1_1['Data da confirmação'] + ' ' + df_1_1['Hora da confirmação']

# Convertendo a nova coluna para tipo datetime
df_1_1['Data_e_Hora'] = pd.to_datetime(df_1_1['Data_e_Hora'])

# Exibindo o DataFrame com a nova coluna datetime
print("\nDataFrame com a coluna 'datetime':")
#display(df_1_1)

<ipython-input-20-766127b167d9>:17: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_1_1['Data_e_Hora'] = pd.to_datetime(df_1_1['Data_e_Hora'])

DataFrame com a coluna 'datetime':

In [21]:
#Juntando os df_1_0 e df_1_1
# Agrupar pelo 'Documento' e pegar a linha com o valor máximo de 'Data_e_Hora' para cada grupo
df_1_1_max = df_1_1.loc[df_1_1.groupby('Documento')['Data_e_Hora'].idxmax()]

#display(df_1_1_max)

# Realizar o merge entre df_1_0 e df_1_1_max com base na coluna 'Documento'
df_merge = df_1_1_max

df_merge.info()
#display(df_merge)

<class 'pandas.core.frame.DataFrame'>
Index: 6698 entries, 15917 to 190783
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Documento            6698 non-null   int64
 1   Data da confirmação  6698 non-null   object
 2   Hora da confirmação  6698 non-null   object
 3   Data_e_Hora          6698 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 261.6+ KB

In [22]:
#Renomeando Colunas

# Renomeando a coluna 'B' para 'Novo_B'
df_merge = df_merge.rename(columns={'Data_e_Hora': 'Data_e_Hora_Fim'})

#display(df_merge)

# Salvando o DataFrame como CSV
#df_merge.to_csv('meu_arquivo.csv', index=False)

#from google.colab import files

# Baixar o arquivo CSV para o computador
#files.download('meu_arquivo.csv')
display(df_merge)

        Documento Data da confirmação Hora da confirmação     Data_e_Hora_Fim
15917   180117611           1/14/2025         10:03:40 PM 2025-01-14 22:03:40
101560  180128019            3/8/2025          3:49:47 PM 2025-03-08 15:49:47
38256   180158249           1/30/2025          9:48:23 PM 2025-01-30 21:48:23
51794   180161781           2/10/2025          9:17:30 AM 2025-02-10 09:17:30
7132    180253283            1/7/2025          3:00:05 PM 2025-01-07 15:00:05
...           ...                 ...                 ...                 ...
189853  183196255           4/30/2025          1:45:07 AM 2025-04-30 01:45:07
190217  183196294           4/30/2025          5:31:13 AM 2025-04-30 05:31:13
190080  183196424           4/30/2025          4:50:00 AM 2025-04-30 04:50:00
190721  183196700           4/30/2025         10:45:31 AM 2025-04-30 10:45:31
190783  183198226           4/30/2025          9:59:00 AM 2025-04-30 09:59:00

[6698 rows x 4 columns]

In [23]:
#Tratamento Fila
df_3_1.info()

# Alterando a coluna 'Documento' de float para object
df_3_1['Documento'] = df_3_1['Documento'].astype('object')

# Substituir valores NaN por uma string vazia
df_3_1['Tempo Fila'] = df_3_1['Tempo Fila'].fillna('')

# Converter para datetime (hora:minuto:segundo)
df_3_1['Tempo Fila'] = pd.to_datetime(df_3_1['Tempo Fila'], format='%H:%M:%S', errors='coerce').dt.time

# Convertendo a coluna para tipo datetime
df_3_1['Data Hora Inicio Operação'] = pd.to_datetime(df_3_1['Data Hora Inicio Operação'])
df_3_1['Data Hora Fim Operação'] = pd.to_datetime(df_3_1['Data Hora Fim Operação'])

# Corrigindo a fórmula de cálculo de Tempo Fila
def calcular_tempo_fila(row):
    # Verifica se Tempo Fila está vazio (NaN ou valor inválido)
    if pd.isna(row['Tempo Fila']) or not isinstance(row['Tempo Fila'], str):
        # Verifica se as colunas de Data Hora Início e Fim não estão vazias
        if pd.notna(row['Data Hora Inicio Operação']) and pd.notna(row['Data Hora Fim Operação']):
            # Calcula a diferença entre Data Hora Fim e Data Hora Início
            tempo_fila = row['Data Hora Fim Operação'] - row['Data Hora Inicio Operação']

            # Retorna a diferença no formato 'HH:MM:SS'
            return str(tempo_fila).split()[2]  # 'HH:MM:SS'
    return row['Tempo Fila']  # Retorna o valor já existente se for válido

# Aplicando a função para calcular o Tempo Fila
df_3_1['Tempo Fila'] = df_3_1.apply(calcular_tempo_fila, axis=1)

# Confirmando Alteração
#df_3_1.info()

display(df_3_1)

<class 'pandas.core.frame.DataFrame'>
Index: 662 entries, 0 to 661
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   indice                     662 non-null    float64
 1   Documento                  662 non-null    float64
 2   Data Hora Inicio Operação  662 non-null    object
 3   Data Hora Fim Operação     659 non-null    object
 4   Status                     662 non-null    object
 5   Tempo Fila                 659 non-null    object
dtypes: float64(2), object(4)
memory usage: 36.2+ KB

<ipython-input-23-a86617f64455>:14: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_3_1['Data Hora Inicio Operação'] = pd.to_datetime(df_3_1['Data Hora Inicio Operação'])
<ipython-input-23-a86617f64455>:15: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_3_1['Data Hora Fim Operação'] = pd.to_datetime(df_3_1['Data Hora Fim Operação'])

,indice,Documento,Data Hora Inicio Operação,Data Hora Fim Operação,Status,Tempo Fila
0,2.0,181787798.0,2025-02-17 01:26:26,2025-02-17 13:26:26,Finalizado,12:00:00
1,3.0,182062973.0,2025-02-28 04:58:06,2025-02-28 16:58:06,Finalizado,12:00:00
2,4.0,182085529.0,2025-02-28 04:58:06,2025-02-28 16:58:06,Finalizado,12:00:00
3,5.0,182044664.0,2025-02-28 07:49:00,2025-02-28 19:49:00,Finalizado,12:00:00
4,6.0,182044665.0,2025-02-28 07:49:00,2025-02-28 19:49:00,Finalizado,12:00:00
...,...,...,...,...,...,...
657,659.0,183108436.0,2025-04-30 07:30:37,2025-04-30 10:09:15,Finalizado,02:38:38
658,660.0,183108454.0,2025-04-30 07:30:37,2025-04-30 10:09:15,Finalizado,02:38:38
659,661.0,183170098.0,2025-04-30 07:30:37,2025-04-30 10:09:15,Finalizado,02:38:38
660,662.0,183174502.0,2025-04-30 07:30:37,2025-04-30 10:09:15,Finalizado,02:38:38
661,663.0,183174511.0,2025-04-30 07:30:37,2025-04-30 10:09:15,Finalizado,02:38:38

In [24]:
#display(df_2_2)
df_2_2.info()
# Transformando INICIO CONFERÊNCIA em date time
df_2_2['INICIO CONFERÊNCIA'] = df_2_2['INICIO CONFERÊNCIA'].replace({
    'erro em ': '', 'não é data': ''
}, regex=False)

# Convertendo corretamente a data com barras
df_2_2['Data_e_Hora_Inicio'] = pd.to_datetime(
    df_2_2['INICIO CONFERÊNCIA'],
    format='%d/%m/%Y %H:%M:%S',
    errors='coerce'
)

# Verificando o resultado
df_2_2.info()
display(df_2_2)

<class 'pandas.core.frame.DataFrame'>
Index: 10061 entries, 0 to 10060
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATA                10061 non-null  object
 1   DOCUMENTO           10061 non-null  object
 2   PLACA               8127 non-null   object
 3   DOCA                9991 non-null   object
 4   STATUS              10060 non-null  object
 5   TIPO DE CARGA       9482 non-null   object
 6   INICIO CONFERÊNCIA  3982 non-null   object
 7   Carga               3752 non-null   object
dtypes: object(8)
memory usage: 707.4+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 10061 entries, 0 to 10060
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATA                10061 non-null  object
 1   DOCUMENTO           10061 non-null  object
 2   PLACA               8127 non-null   object
 3   DOCA                9991 non-null   object
 4   STATUS              10060 non-null  object
 5   TIPO DE CARGA       9482 non-null   object
 6   INICIO CONFERÊNCIA  3982 non-null   object
 7   Carga               3752 non-null   object
 8   Data_e_Hora_Inicio  3527 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(8)
memory usage: 786.0+ KB

,DATA,DOCUMENTO,PLACA,DOCA,STATUS,TIPO DE CARGA,INICIO CONFERÊNCIA,Carga,Data_e_Hora_Inicio
0,04/07/2024,200014984,NaN,DK 19,FINALIZADA,CARGA BATIDA,NaN,NaN,NaT
1,04/07/2024,200014984,NaN,DK 19,FINALIZADA,CARGA BATIDA,NaN,NaN,NaT
2,09/07/2024,180087643,NaN,DK 19,FINALIZADA,CARGA PALETIZADA,NaN,NaN,NaT
3,16/07/2024,180089148,NaN,DK 19,FINALIZADA,CARGA PALETIZADA,NaN,NaN,NaT
4,16/07/2024,180090777,NaN,DK 19,FINALIZADA,CARGA PALETIZADA,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...
10056,30/04/2025,183063907,EGK8860,DK 04,AG.CONFERENCIA,CARGA PALETIZADA,30/04/2025 10:50:28,45777EGK8860,2025-04-30 10:50:28
10057,30/04/2025,183063908,EGK8860,DK 04,AG.CONFERENCIA,CARGA PALETIZADA,30/04/2025 10:50:28,45777EGK8860,2025-04-30 10:50:28
10058,30/04/2025,183093181,EGK8860,DK 04,AG.CONFERENCIA,CARGA PALETIZADA,30/04/2025 11:01:42,45777EGK8860,2025-04-30 11:01:42
10059,30/04/2025,183105896,EGK8860,DK 04,AG.CONFERENCIA,CARGA PALETIZADA,30/04/2025 11:01:42,45777EGK8860,2025-04-30 11:01:42
10060,30/04/2025,183191558,EGK8860,DK 04,AG.CONFERENCIA,CARGA PALETIZADA,30/04/2025 11:01:43,45777EGK8860,2025-04-30 11:01:43

In [25]:
#Merge Controle Inbound

# Usando fillna() para substituir NaN na PLACA por uma string vazia, e depois concatenar
#df_2_2['Carga_Dia'] = df_2_2['DATA'] + '_' + df_2_2['PLACA'].fillna('')

df_2_2 = df_2_2.rename(columns={'DOCUMENTO': 'Documento'})


#Merge com o DF_merge
df_merge_final = pd.merge(df_2_2, df_merge, on='Documento')

#Merge com o df_3_1
df_merge_final = pd.merge(df_merge_final, df_3_1, on='Documento', how='left')

# Calculando a diferença entre 'Data_e_Hora_Fim' e 'Data_e_Hora_Inicio'
df_merge_final['Diferenca'] = df_merge_final['Data_e_Hora_Fim'] - df_merge_final['Data_e_Hora_Inicio']

# Calculando a diferença em horas (convertendo de timedelta para horas)
df_merge_final['Diferenca_em_Horas'] = df_merge_final['Diferenca'].dt.total_seconds() / 3600

import pandas as pd
import numpy as np
from datetime import timedelta

# Supondo que df_merge_final['DataHoraInicio'] seja a coluna com a data e hora de início
def calcular_sla(row):
    # Obter o dia da semana e a hora
    dia_da_semana = row['Data_e_Hora_Inicio'].weekday()  # 0 = segunda-feira, 4 = sexta-feira, 6 = domingo
    hora_inicio = row['Data_e_Hora_Inicio'].hour

    # Verificar se está entre sexta-feira após as 18h e domingo até as 23h
    if (dia_da_semana == 4 and hora_inicio >= 18) or (dia_da_semana == 5) or (dia_da_semana == 6 and hora_inicio <= 23):
        # Se estiver no intervalo, considera SLA de 72 horas
        limite_sla = timedelta(hours=72)
    else:
        # Caso contrário, considera SLA de 24 horas
        limite_sla = timedelta(hours=24)

    # Calcular a diferença de tempo
    diferenca = row['Diferenca_em_Horas']  # Supondo que já tenha a diferença de horas calculada em outra coluna

    # Definir o SLA Status
    if diferenca > limite_sla.total_seconds() / 3600:  # Convertendo limite_sla para horas
        return 'Fora do SLA'
    else:
        return 'Dentro do SLA'

# Aplicando a função para criar a coluna 'SLA_Status'
df_merge_final['SLA_Status'] = df_merge_final.apply(calcular_sla, axis=1)


# Tente converter as datas, transformando as inválidas em NaT (Not a Time)
df_merge_final['DATA'] = pd.to_datetime(df_merge_final['DATA'], format='%d/%m/%Y', errors='coerce')

#df_merge_final.info()

#display(df_merge_final)

In [26]:
#Limpando o df_merge_final e ultimos ajustes

# Convertendo a coluna 'outra_coluna' para datetime
df_2_2['DATA'] = pd.to_datetime(df_2_2['DATA'], format='%d/%m/%Y', errors='coerce')

# Renomeando a coluna 'B' para 'Novo_B'
df_merge_final = df_merge_final.rename(columns={'Data Hora Inicio Operação': 'Data_e_Hora_Inicio_Fila', 'Data Hora Fim Operação': 'Data_e_Hora_Fim_Fila','DATA': 'Data_Agenda' })

# Para remover colunas específicas, use o método .drop()
df_merge_final = df_merge_final.drop(columns=['indice','Diferenca_em_Horas'])

# Renomeando + colunas
df_merge_final = df_merge_final.rename(columns={'SLA_Status': 'SLA_Status_Conf_Arma'})

# Calculo final Status_SLA_Descarregamento

In [27]:
df_merge_final = df_merge_final.loc[
    (df_merge_final['STATUS'] == 'FINALIZADA') &
    (df_merge_final['Data_e_Hora_Inicio'].notna())
]


display(df_merge_final)

,Data_Agenda,Documento,PLACA,DOCA,STATUS,TIPO DE CARGA,INICIO CONFERÊNCIA,Carga,Data_e_Hora_Inicio,Data da confirmação,Hora da confirmação,Data_e_Hora_Fim,Data_e_Hora_Inicio_Fila,Data_e_Hora_Fim_Fila,Status,Tempo Fila,Diferenca,SLA_Status_Conf_Arma
2965,2025-02-17,181787798,SWT3F46,DK 04,FINALIZADA,CARGA PALETIZADA,26/02/2025 17:00:00,NaN,2025-02-26 17:00:00,3/30/2025,7:02:59 AM,2025-03-30 07:02:59,2025-02-17 01:26:26,2025-02-17 13:26:26,Finalizado,12:00:00,31 days 14:02:59,Fora do SLA
2967,2025-02-27,182032458,CTA5E01,DK 08,FINALIZADA,CARGA BATIDA,27/02/2025 09:00:00,66037,2025-02-27 09:00:00,3/30/2025,7:35:50 AM,2025-03-30 07:35:50,NaT,NaT,NaN,NaN,30 days 22:35:50,Fora do SLA
2968,2025-02-26,181461355,AXT9B18,DK 12,FINALIZADA,CARGA PALETIZADA,27/02/2025 09:00:00,62816,2025-02-27 09:00:00,3/30/2025,10:02:57 AM,2025-03-30 10:02:57,NaT,NaT,NaN,NaN,31 days 01:02:57,Fora do SLA
2969,2025-02-27,181943762,AXN2C16,DK 11,FINALIZADA,CARGA BATIDA,27/02/2025 21:00:00,2252,2025-02-27 21:00:00,3/30/2025,3:05:29 PM,2025-03-30 15:05:29,NaT,NaT,NaN,NaN,30 days 18:05:29,Fora do SLA
2972,2025-02-28,182049597,AXZ6B11,DK 18,FINALIZADA,CARGA PALETIZADA,28/02/2025 04:00:00,67400,2025-02-28 04:00:00,2/28/2025,7:41:18 AM,2025-02-28 07:41:18,NaT,NaT,NaN,NaN,0 days 03:41:18,Dentro do SLA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6409,2025-04-29,183105236,TBY2G55,DK 23,FINALIZADA,CARGA BATIDA,29/04/2025 16:06:24,45776TBY2G55,2025-04-29 16:06:24,4/30/2025,1:45:30 AM,2025-04-30 01:45:30,NaT,NaT,NaN,NaN,0 days 09:39:06,Dentro do SLA
6410,2025-04-29,183196083,TBY2G55,DK 23,FINALIZADA,CARGA BATIDA,29/04/2025 16:06:25,45776TBY2G55,2025-04-29 16:06:25,4/30/2025,1:52:44 AM,2025-04-30 01:52:44,NaT,NaT,NaN,NaN,0 days 09:46:19,Dentro do SLA
6413,2025-04-29,183196294,AXZ9B91,DK 11,FINALIZADA,CARGA BATIDA,29/04/2025 17:42:46,76050,2025-04-29 17:42:46,4/30/2025,5:31:13 AM,2025-04-30 05:31:13,NaT,NaT,NaN,NaN,0 days 11:48:27,Dentro do SLA
6415,2025-04-29,183089093,SEL9F03,DK 14,FINALIZADA,CARGA PALETIZADA,29/04/2025 18:47:33,75997,2025-04-29 18:47:33,4/29/2025,11:41:54 PM,2025-04-29 23:41:54,NaT,NaT,NaN,NaN,0 days 04:54:21,Dentro do SLA
6416,2025-04-29,183089094,SEL9F03,DK 14,FINALIZADA,CARGA PALETIZADA,29/04/2025 18:47:34,75997,2025-04-29 18:47:34,4/29/2025,11:53:56 PM,2025-04-29 23:53:56,NaT,NaT,NaN,NaN,0 days 05:06:22,Dentro do SLA

In [28]:
#gerando DF filtrado só com os fora do SLA

#definindo a coluna de finalização do turno

# Calculando o total de minutos a partir da coluna 'Data_e_Hora_Fim'
df_merge_final['Total_Minutos'] = df_merge_final['Data_e_Hora_Fim'].dt.hour * 60 + df_merge_final['Data_e_Hora_Fim'].dt.minute

# Lógica para determinar o turno
df_merge_final['Turno'] = df_merge_final['Data_e_Hora_Fim'].apply(lambda x: (
    "1º Turno" if x.weekday() == 4 and (x.hour * 60 + x.minute) >= 351 and (x.hour * 60 + x.minute) < 720 else
    "2º Turno" if x.weekday() == 4 and (x.hour * 60 + x.minute) >= 721 and (x.hour * 60 + x.minute) < 1080 else
    "3º Turno" if x.weekday() == 4 else
    "1º Turno" if (x.hour * 60 + x.minute) >= 351 and (x.hour * 60 + x.minute) < 860 else
    "2º Turno" if (x.hour * 60 + x.minute) >= 861 and (x.hour * 60 + x.minute) < 1360 else
    "3º Turno"
))

# Concatenando as colunas de data e placa em uma nova coluna
# Convertendo as colunas de data para string antes de concatenar
df_merge_final['Chave'] = df_merge_final['Documento'].astype(str) + '-' + \
                          df_merge_final['Data_e_Hora_Inicio_Fila'].astype(str) + '-' + \
                          df_merge_final['Data_e_Hora_Fim_Fila'].astype(str) + '-' + \
                          df_merge_final['Status'].astype(str) + '-' + \
                          df_merge_final['Tempo Fila'].astype(str) + '-' + \
                          df_merge_final['Data_Agenda'].astype(str) + '-' + \
                          df_merge_final['PLACA'].astype(str) + '-' + \
                          df_merge_final['DOCA'].astype(str) + '-' + \
                          df_merge_final['STATUS'].astype(str) + '-' + \
                          df_merge_final['TIPO DE CARGA'].astype(str) + '-' + \
                          df_merge_final['Data_e_Hora_Inicio'].dt.strftime('%Y-%m-%d %H:%M:%S') + '-' + \
                          df_merge_final['Data_e_Hora_Fim'].dt.strftime('%Y-%m-%d %H:%M:%S') + '-' + \
                          df_merge_final['Diferenca'].astype(str) + '-' + \
                          df_merge_final['SLA_Status_Conf_Arma'].astype(str)



#display(df_merge_final)
#display(df_fora_do_SLA)

<ipython-input-28-816ba0b78c69>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge_final['Total_Minutos'] = df_merge_final['Data_e_Hora_Fim'].dt.hour * 60 + df_merge_final['Data_e_Hora_Fim'].dt.minute
<ipython-input-28-816ba0b78c69>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge_final['Turno'] = df_merge_final['Data_e_Hora_Fim'].apply(lambda x: (
<ipython-input-28-816ba0b78c69>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge_final['Chave'] = df_merge_final['Documento'].astype(str) + '-' + \

In [29]:
df_merge_final.drop(['INICIO CONFERÊNCIA', 'Data da confirmação', 'Hora da confirmação', 'Data da confirmação', 'Total_Minutos'], axis=1, inplace=True)

df_merge_final['Documento'] = df_merge_final['Documento'].astype('Int64')  # 'Int64' mantém valores nulos

display(df_merge_final)

# Definindo a ordem das colunas na planilha
# Nova ordem que você quer
nova_ordem = ['Documento', 'Data_Agenda', 'PLACA', 'DOCA', 'STATUS', 'TIPO DE CARGA', 'Data_e_Hora_Inicio', 'Data_e_Hora_Inicio_Fila', 'Data_e_Hora_Fim_Fila', 'Status', 'Tempo Fila', 'Data_e_Hora_Fim', 'Diferenca', 'SLA_Status_Conf_Arma', 'Turno', 'Chave']

# Reordenando
df_merge_final = df_merge_final[nova_ordem]

<ipython-input-29-bf8872af9084>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge_final.drop(['INICIO CONFERÊNCIA', 'Data da confirmação', 'Hora da confirmação', 'Data da confirmação', 'Total_Minutos'], axis=1, inplace=True)
<ipython-input-29-bf8872af9084>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge_final['Documento'] = df_merge_final['Documento'].astype('Int64')  # 'Int64' mantém valores nulos

,Data_Agenda,Documento,PLACA,DOCA,STATUS,TIPO DE CARGA,Carga,Data_e_Hora_Inicio,Data_e_Hora_Fim,Data_e_Hora_Inicio_Fila,Data_e_Hora_Fim_Fila,Status,Tempo Fila,Diferenca,SLA_Status_Conf_Arma,Turno,Chave
2965,2025-02-17,181787798,SWT3F46,DK 04,FINALIZADA,CARGA PALETIZADA,NaN,2025-02-26 17:00:00,2025-03-30 07:02:59,2025-02-17 01:26:26,2025-02-17 13:26:26,Finalizado,12:00:00,31 days 14:02:59,Fora do SLA,1º Turno,181787798-2025-02-17 01:26:26-2025-02-17 13:26...
2967,2025-02-27,182032458,CTA5E01,DK 08,FINALIZADA,CARGA BATIDA,66037,2025-02-27 09:00:00,2025-03-30 07:35:50,NaT,NaT,NaN,NaN,30 days 22:35:50,Fora do SLA,1º Turno,182032458-NaT-NaT-nan-nan-2025-02-27-CTA5E01-D...
2968,2025-02-26,181461355,AXT9B18,DK 12,FINALIZADA,CARGA PALETIZADA,62816,2025-02-27 09:00:00,2025-03-30 10:02:57,NaT,NaT,NaN,NaN,31 days 01:02:57,Fora do SLA,1º Turno,181461355-NaT-NaT-nan-nan-2025-02-26-AXT9B18-D...
2969,2025-02-27,181943762,AXN2C16,DK 11,FINALIZADA,CARGA BATIDA,2252,2025-02-27 21:00:00,2025-03-30 15:05:29,NaT,NaT,NaN,NaN,30 days 18:05:29,Fora do SLA,2º Turno,181943762-NaT-NaT-nan-nan-2025-02-27-AXN2C16-D...
2972,2025-02-28,182049597,AXZ6B11,DK 18,FINALIZADA,CARGA PALETIZADA,67400,2025-02-28 04:00:00,2025-02-28 07:41:18,NaT,NaT,NaN,NaN,0 days 03:41:18,Dentro do SLA,1º Turno,182049597-NaT-NaT-nan-nan-2025-02-28-AXZ6B11-D...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6409,2025-04-29,183105236,TBY2G55,DK 23,FINALIZADA,CARGA BATIDA,45776TBY2G55,2025-04-29 16:06:24,2025-04-30 01:45:30,NaT,NaT,NaN,NaN,0 days 09:39:06,Dentro do SLA,3º Turno,183105236-NaT-NaT-nan-nan-2025-04-29-TBY2G55-D...
6410,2025-04-29,183196083,TBY2G55,DK 23,FINALIZADA,CARGA BATIDA,45776TBY2G55,2025-04-29 16:06:25,2025-04-30 01:52:44,NaT,NaT,NaN,NaN,0 days 09:46:19,Dentro do SLA,3º Turno,183196083-NaT-NaT-nan-nan-2025-04-29-TBY2G55-D...
6413,2025-04-29,183196294,AXZ9B91,DK 11,FINALIZADA,CARGA BATIDA,76050,2025-04-29 17:42:46,2025-04-30 05:31:13,NaT,NaT,NaN,NaN,0 days 11:48:27,Dentro do SLA,3º Turno,183196294-NaT-NaT-nan-nan-2025-04-29-AXZ9B91-D...
6415,2025-04-29,183089093,SEL9F03,DK 14,FINALIZADA,CARGA PALETIZADA,75997,2025-04-29 18:47:33,2025-04-29 23:41:54,NaT,NaT,NaN,NaN,0 days 04:54:21,Dentro do SLA,3º Turno,183089093-NaT-NaT-nan-nan-2025-04-29-SEL9F03-D...
6416,2025-04-29,183089094,SEL9F03,DK 14,FINALIZADA,CARGA PALETIZADA,75997,2025-04-29 18:47:34,2025-04-29 23:53:56,NaT,NaT,NaN,NaN,0 days 05:06:22,Dentro do SLA,3º Turno,183089094-NaT-NaT-nan-nan-2025-04-29-SEL9F03-D...

In [30]:
!pip install gspread_dataframe

from gspread_dataframe import set_with_dataframe

Requirement already satisfied: gspread_dataframe in /usr/local/lib/python3.11/dist-packages (4.0.0)
Requirement already satisfied: gspread>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from gspread_dataframe) (6.2.0)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from gspread_dataframe) (2.2.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from gspread_dataframe) (1.17.0)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from gspread>=3.0.0->gspread_dataframe) (2.39.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from gspread>=3.0.0->gspread_dataframe) (1.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->gspread_dataframe) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->gspread_dataframe) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->gspread_dataframe) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->gspread_dataframe) (2025.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread>=3.0.0->gspread_dataframe) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread>=3.0.0->gspread_dataframe) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.12.0->gspread>=3.0.0->gspread_dataframe) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread_dataframe) (2.0.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread>=3.0.0->gspread_dataframe) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread_dataframe) (3.2.2)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread_dataframe) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread_dataframe) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread_dataframe) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread_dataframe) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread>=3.0.0->gspread_dataframe) (2025.1.31)

In [31]:
# Salvando o DataFrame como CSV
#df_3_1.to_csv('df_3_1.csv', index=False)

# Importando o módulo necessário para download no Colab
#from google.colab import files

# Baixando o arquivo para o computador
#files.download('df_3_1.csv')
#df_3_1.info()

In [32]:
#Salvando em um sheets especifico

# Abre a planilha existente pelo nome (você pode mudar o nome da planilha conforme necessário)
spreadsheet_id = '1jwkcs8iecQFIiInhCxslPzKlPvUMZvgKfjXMa4tw1NA'

# Abrir a planilha pelo ID
spreadsheet = gc.open_by_key(spreadsheet_id)

# Cria ou acessa uma aba específica dentro da planilha
Analise_SLA = spreadsheet.worksheet('Analise_SLA')  # Substitua pelo nome da aba

# Escreve os DataFrames na aba correspondente
set_with_dataframe(Analise_SLA, df_merge_final)  # Salva df_merge_final na aba especificada